# Generated by Django 4.0.6 on 2022-08-23 08:48

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2022, 8, 23, 8, 52, 59, 920047, tzinfo=utc))),
                ('urlname', models.CharField(max_length=10, unique=True)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
