# Generated by Django 4.0.6 on 2022-08-23 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 9, 9, 50, 447261, tzinfo=utc)),
        ),
    ]
