# Generated by Django 4.0.6 on 2022-08-23 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0002_alter_file_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 9, 17, 26, 805272, tzinfo=utc)),
        ),
    ]
