# Generated by Django 4.1.7 on 2023-03-01 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0003_alter_file_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 6, 1, 40, 535517, tzinfo=datetime.timezone.utc)),
        ),
    ]
