# Generated by Django 4.1.7 on 2023-03-07 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0004_alter_file_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Email',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 5, 42, 27, 170792, tzinfo=datetime.timezone.utc)),
        ),
    ]
