# Generated by Django 4.1.7 on 2023-03-09 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0005_file_email_alter_file_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 6, 10, 7, 489704, tzinfo=datetime.timezone.utc)),
        ),
    ]
