# Generated by Django 4.1.7 on 2023-03-09 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0006_alter_file_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 8, 32, 49, 301133, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='urlname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
