# Generated by Django 4.1.7 on 2023-03-09 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0007_alter_file_email_alter_file_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 9, 48, 48, 869357, tzinfo=datetime.timezone.utc)),
        ),
    ]
