# Generated by Django 4.1.7 on 2023-03-09 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0009_alter_file_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 13, 1, 21, 578141, tzinfo=datetime.timezone.utc)),
        ),
    ]
