# Generated by Django 4.1.7 on 2023-03-21 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0010_remove_file_name_alter_file_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 12, 6, 26, 729698, tzinfo=datetime.timezone.utc)),
        ),
    ]
