# Generated by Django 4.1.7 on 2023-04-18 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0011_alter_file_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='docx_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docx_file')),
            ],
        ),
        migrations.CreateModel(
            name='pdf_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_file')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 12, 16, 29, 852415, tzinfo=datetime.timezone.utc)),
        ),
    ]
