# Generated by Django 4.1.7 on 2023-04-19 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0012_docx_file_pdf_file_alter_file_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 11, 54, 30, 964240, tzinfo=datetime.timezone.utc)),
        ),
    ]
