# Generated by Django 4.1.7 on 2023-04-19 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0013_alter_file_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 12, 19, 5, 715589, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='upload/files'),
        ),
    ]
