# Generated by Django 4.1.7 on 2023-04-19 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0014_alter_file_expires_at_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 12, 32, 0, 394921, tzinfo=datetime.timezone.utc)),
        ),
    ]
