# Generated by Django 4.1.7 on 2023-04-27 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0017_alter_file_expires_at_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 6, 43, 25, 927512, tzinfo=datetime.timezone.utc)),
        ),
    ]
