# Generated by Django 4.1.7 on 2023-04-28 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0019_alter_file_expires_at_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_file', models.FileField(upload_to='word_files/')),
                ('pdf_file', models.FileField(upload_to='pdf_files/')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 10, 59, 42, 775668, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='upload/files/'),
        ),
    ]
