# Generated by Django 4.1.7 on 2023-04-28 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0020_convertedfile_alter_file_expires_at_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 11, 0, 31, 412781, tzinfo=datetime.timezone.utc)),
        ),
    ]
