# Generated by Django 4.1.7 on 2023-05-02 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0021_alter_file_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_file', models.FileField(upload_to='word_files/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
            ],
        ),
        migrations.DeleteModel(
            name='ConvertedFile',
        ),
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 10, 24, 31, 389139, tzinfo=datetime.timezone.utc)),
        ),
    ]
