# Generated by Django 4.1.7 on 2023-05-04 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0023_pdf_alter_file_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 10, 46, 52, 302928, tzinfo=datetime.timezone.utc)),
        ),
    ]
