# Generated by Django 4.1.7 on 2023-06-03 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0025_alter_file_expires_at_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 4, 23, 54, 747205, tzinfo=datetime.timezone.utc)),
        ),
    ]
