# Generated by Django 4.1.7 on 2023-06-03 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareit', '0027_alter_file_expires_at_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 6, 56, 4, 828140, tzinfo=datetime.timezone.utc)),
        ),
    ]
